"""Shared Core enums. Python types are not language-neutral architectural contracts."""

from enum import Enum, IntEnum


class ActorType(Enum):
    HUMAN_OPERATOR = "HUMAN_OPERATOR"
    CONTROL_PLANE = "CONTROL_PLANE"
    WORKER = "WORKER"
    INTEGRATION = "INTEGRATION"


class AuthorizationSourceState(Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class ScopeDecision(Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_HUMAN_REVIEW = "REQUIRE_HUMAN_REVIEW"


class ScopeRuleEffect(Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class SideEffectLevel(IntEnum):
    LEVEL_0 = 0
    LEVEL_1 = 1
    LEVEL_2 = 2
    LEVEL_3 = 3


class ApprovalDecision(Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"


class ExecutionDecisionKind(Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    REQUIRE_HUMAN_REVIEW = "REQUIRE_HUMAN_REVIEW"


class ReasonCode(Enum):
    ALLOWED = "ALLOWED"
    AUTHORIZATION_MISSING = "AUTHORIZATION_MISSING"
    AUTHORIZATION_INACTIVE = "AUTHORIZATION_INACTIVE"
    SCOPE_DENIED = "SCOPE_DENIED"
    SCOPE_NOT_EXPLICITLY_ALLOWED = "SCOPE_NOT_EXPLICITLY_ALLOWED"
    SCOPE_AMBIGUOUS = "SCOPE_AMBIGUOUS"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    BUDGET_MISMATCH = "BUDGET_MISMATCH"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_REJECTED = "APPROVAL_REJECTED"
    APPROVAL_INVALID_ACTOR = "APPROVAL_INVALID_ACTOR"
    APPROVAL_SUBJECT_MISMATCH = "APPROVAL_SUBJECT_MISMATCH"
    APPROVAL_NOT_RECORDED = "APPROVAL_NOT_RECORDED"
    SIDE_EFFECT_LEVEL_DENIED = "SIDE_EFFECT_LEVEL_DENIED"
